version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    env_file: .env
    
  db:
    image: postgis/postgis:12-3.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  