# Generated by Django 3.2.6 on 2022-05-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220524_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shopify_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
