# Generated by Django 3.2.6 on 2022-05-24 15:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_shopify_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartsession',
            name='checkout_id',
        ),
        migrations.RemoveField(
            model_name='cartsession',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartsession',
            name='quantity',
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cartsession')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
        ),
    ]
