# Generated by Django 3.2.6 on 2022-06-30 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_image_productsection_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shopify_id',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='productcolour',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colours', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='productsection',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product'),
        ),
    ]
