# Generated by Django 3.2.6 on 2022-07-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
