# Generated by Django 3.2.6 on 2022-07-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='item_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
