# Generated by Django 3.2.6 on 2022-07-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_affiliate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
