# Generated by Django 3.2.6 on 2022-09-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_contactsubmission_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shopify_id',
            field=models.CharField(max_length=255),
        ),
    ]
